// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Constants
{
        public const string achievement_cannon_hero_ii = "CgkIsKHfyP4TEAIQCw"; // <GPGSID>
        public const string achievement_sunset_admirer = "CgkIsKHfyP4TEAIQAg"; // <GPGSID>
        public const string achievement_cannon_hero = "CgkIsKHfyP4TEAIQCg"; // <GPGSID>
        public const string achievement_another_beautiful_day = "CgkIsKHfyP4TEAIQBQ"; // <GPGSID>
        public const string achievement_cannon_specialist = "CgkIsKHfyP4TEAIQBg"; // <GPGSID>
        public const string achievement_night_flyer = "CgkIsKHfyP4TEAIQAw"; // <GPGSID>
        public const string achievement_flying_mentor = "CgkIsKHfyP4TEAIQBw"; // <GPGSID>
        public const string achievement_cannon_master = "CgkIsKHfyP4TEAIQCA"; // <GPGSID>
        public const string achievement_beginner_self_launcher = "CgkIsKHfyP4TEAIQAQ"; // <GPGSID>
        public const string achievement_sky_conqueror = "CgkIsKHfyP4TEAIQCQ"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIsKHfyP4TEAIQDQ"; // <GPGSID>
        public const string achievement_morning_flyer = "CgkIsKHfyP4TEAIQBA"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkIsKHfyP4TEAIQAA"; // <GPGSID>

}

